services:
  docker_db_postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: Xyz123Xyz123Xyz123
      POSTGRES_DB: my_test_dbA
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres_data: